### ISSUE TITLE
[ShadyDOM] With`preferPerformance` enabled <slot> elements may only be added inside document fragments

### ISSUE THREAD

**Issue by sorvell** [webcomponents/polyfills#99] opened 2019-04-24 22:34 UTC
The intention of this optimization was to be able to avoid walking the entire node subtree for <slot> elements whenever any node is added to the dom inside a shadowRoot. It creates a pretty big footgun, however. 

Either some other heuristic should be used or perhaps a bespoke API to force slot finding should be introduced.

**Comment by azakus** [comment] 2019-06-13 00:56
Duplicate of #92

**Closed by azakus** 2019-06-13 00:56 UTC
