### ISSUE TITLE
[WCJS] Support es module import statement

### ISSUE THREAD

**Issue by ebidel** [webcomponents/polyfills#52] opened 2018-09-04 17:43 UTC
Currently you cannot simply `import` the loader like this:

```js
import 'https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/webcomponents-loader.js';
```

The loader requires a `<script>` tag. For projects that don't require bundling, it would be nice to support this way to load the lib.

**Comment by azakus** [comment] 2019-06-13 00:37
Duplicate of #52

**Closed by azakus** 2019-06-13 00:37 UTC

**Comment by AStoker** [comment] 2019-06-14 19:28
@azakus , this is issue #52. Did you mean to add that comment and close a different issue?
