### ISSUE TITLE
IE11 - CSS variables declared at :root are blanked out in output

### ISSUE THREAD

**Issue by pnewsam** [webcomponents/polyfills#9] opened 2019-02-28 21:16 UTC
Not 100% sure this is a ShadyCSS issue but it seems to be.

In our project we have CSS variables that are declared at the document `:root`. I would like to leave the declarations there, so that updates can be made seamlessly post-build. This as opposed to having them declared within the `:host` of a given component's shadow instance. However, it seems that any references to those variables are being blanked out by ShadyCSS, presumably because they are being replaced with the value assigned to those variables locally, which is nought. This eliminates the possibility of applying a polyfill post-facto and getting those variable references replaced...

Are these observations correct, and if so, are there any plans to make that behavior configurable?

**Comment by azakus** [comment] 2019-06-12 21:46
Duplicate of #37

**Closed by azakus** 2019-06-12 21:46 UTC
