### ISSUE TITLE
Add changelog (leverage lerna + conventional-commits)

### ISSUE THREAD

**Issue by dogoku** [webcomponents/polyfills#232] opened 2019-11-17 14:58 UTC
It's nice to see the polyfills moved to a monorepo, but it's a shame to not have a changelog for each of the polyfills.

Since you are using `lerna` to manage the monorepo, it should be easy to have it generate changelogs for you, assuming you start using conventional commits.

It just takes a bit of discipline when writing the commit messages but you get changelogs for free, just by running `lerna publish --conventional-commits`. Not only will lerna generate the changelogs for you, but it will also automatically bump your version (based on semantic versioning)

Think about it :)

**Comment by aomarks** [comment] 2020-04-22 04:08
Dupe of https://github.com/webcomponents/polyfills/issues/54

**Closed by aomarks** 2020-04-22 04:08 UTC
