### ISSUE TITLE
Please add change log

### ISSUE THREAD

**Issue by cronon** [webcomponents/polyfills#255] opened 2020-01-29 12:41 UTC
Please add change log files to the packages. Without them it's really hard to understand what is different in new releases

**Comment by web-padawan** [comment] 2020-01-29 14:40
See also #54 #159 #232

**Comment by aomarks** [comment] 2020-04-22 04:08
Dupe of https://github.com/webcomponents/polyfills/issues/54

**Closed by aomarks** 2020-04-22 04:08 UTC
