### ISSUE TITLE
Publish scoped-custom-element-registry

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/polyfills#426] opened 2021-02-12 19:25 UTC
We need to publish a `0.0.1` release of https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry to npm as `@webcomponents/scoped-custom-element-registry`.

This should not be integrated with `webcomponents.js` as it is a speculative polyfill.

**Comment by bicknellr** [comment] 2021-02-12 21:34
Dupe of #424 :)

**Closed by bicknellr** 2021-02-12 21:34 UTC
Labels: Focus Area: Standards & Polyfills, Type: Maintenance
