### ISSUE TITLE
Setup CHANGELOGs and check for updating CHANGELOG with PRs

### ISSUE THREAD

**Issue by dfreedm** [webcomponents/polyfills#159] opened 2019-06-25 18:39 UTC

**Comment by abdonrd** [comment] 2019-09-20 07:39
I just see the new version: https://github.com/webcomponents/polyfills/commit/27ef16d371bf9eb12ec7ac857633cc8d68f8c396

There are no changelogs?

**Comment by aomarks** [comment] 2020-04-22 04:08
Dupe of https://github.com/webcomponents/polyfills/issues/54

**Closed by aomarks** 2020-04-22 04:08 UTC
Labels: Severity: High
